project:
  type: website
  output-dir: docs

website:
  title: "Dr. Heather Zinn Brooks"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - publications.qmd
      - teaching.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



